### ISSUE TITLE
Support label selectors

### ISSUE THREAD

**Issue by chriskirkland** [CanopyTax/ckube#2]
It would be nice to support selecting pods via labels as well as pod prefix.  For instance, if I want to tail logs on all of my backend pods from different services (i.e. `ckube logs -l tier=backend`) or change a setting in all of my frontend pods (i.e. `ckube exec -l tier=frontend ...`).

**Comment by devonmoss** [comment]
The `-l` selector is now functional with `ls, logs, top`. I am trying to work through some strangeness with `exec` due to positional arguments. Pull requests accepted :)

**Comment by devonmoss** [comment]
no action on this so I am closing.
