### ISSUE TITLE
Windows Binaries?

### ISSUE THREAD

**Issue by DWSR** [CanopyTax/ckube#9]
As this is a Go project, would it be possible to get Windows binaries built as well from the CI system? I'm interacting with Kubernetes almost exclusively from PowerShell/Windows and would love to not have to build this myself.

**Comment by devonmoss** [comment]
I had issues getting TravisCI to build the binaries for Windows. [Here is the output of one such build](https://travis-ci.org/CanopyTax/ckube/jobs/303807577). Do you know what this error means? I would love to have them included but I don't have a Windows environment or experience resolving Windows specific issues. If using the linux subsystem in Windows is not an option I happily accept pull requests if you do get them built.

**Comment by DWSR** [comment]
@devonmoss Was simply a missing Windows-specific dependency (I didn't know that was a thing you could do).

Opened #11 to address.

**Comment by devonmoss** [comment]
@DWSR Thanks a lot for your PR. The TravisCI build has been updated to build Windows binaries and include them in the releases and thanks to your changes it appears to be working successfully. The Windows binaries are available starting with [v0.4.3](https://github.com/CanopyTax/ckube/releases/tag/v0.4.3)
